// A curated pack of short, board-friendly quotes (public domain attributions).
// Rotates by hour so it changes through the day but stays stable per viewing.
const QUOTES = [
  ["THE ONLY WAY OUT IS THROUGH", "ROBERT FROST"],
  ["WELL BEGUN IS HALF DONE", "ARISTOTLE"],
  ["MAKE EACH DAY YOUR MASTERPIECE", "JOHN WOODEN"],
  ["SIMPLICITY IS THE ULTIMATE SOPHISTICATION", "LEONARDO DA VINCI"],
  ["WHETHER YOU THINK YOU CAN OR YOU CANNOT YOU ARE RIGHT", "HENRY FORD"],
  ["A JOURNEY OF A THOUSAND MILES BEGINS WITH A SINGLE STEP", "LAO TZU"],
  ["WHAT WE THINK WE BECOME", "BUDDHA"],
  ["ACTION IS THE FOUNDATION OF SUCCESS", "PABLO PICASSO"],
  ["FORTUNE FAVORS THE BOLD", "VIRGIL"],
  ["KNOW THYSELF", "SOCRATES"],
  ["NOTHING VENTURED NOTHING GAINED", "GEOFFREY CHAUCER"],
  ["THE BEST TIME TO PLANT A TREE WAS TWENTY YEARS AGO THE SECOND BEST TIME IS NOW", "CHINESE PROVERB"],
  ["IF YOU WANT TO GO FAR GO TOGETHER", "AFRICAN PROVERB"],
  ["PERFECTION IS ATTAINED WHEN THERE IS NOTHING LEFT TO TAKE AWAY", "ANTOINE DE SAINT EXUPERY"],
  ["WE ARE WHAT WE REPEATEDLY DO", "WILL DURANT"],
  ["THE UNEXAMINED LIFE IS NOT WORTH LIVING", "SOCRATES"],
  ["HOPE IS THE THING WITH FEATHERS", "EMILY DICKINSON"],
  ["COURAGE IS GRACE UNDER PRESSURE", "ERNEST HEMINGWAY"],
  ["EVERYTHING YOU CAN IMAGINE IS REAL", "PABLO PICASSO"],
  ["TURN YOUR WOUNDS INTO WISDOM", "OPRAH WINFREY"],
  ["WHEREOF ONE CANNOT SPEAK THEREOF ONE MUST BE SILENT", "WITTGENSTEIN"],
  ["TIME IS THE MOST VALUABLE THING A MAN CAN SPEND", "THEOPHRASTUS"],
  ["ORDER AND SIMPLIFICATION ARE THE FIRST STEPS TOWARD MASTERY", "THOMAS MANN"],
  ["YOU MISS ONE HUNDRED PERCENT OF THE SHOTS YOU DO NOT TAKE", "WAYNE GRETZKY"],
  ["THE OCEAN STIRS THE HEART INSPIRES THE IMAGINATION", "WYLAND"],
  ["STAY HUNGRY STAY FOOLISH", "WHOLE EARTH CATALOG"],
  ["LESS BUT BETTER", "DIETER RAMS"],
  ["SLOW IS SMOOTH SMOOTH IS FAST", "PROVERB"],
  ["DO THE HARD THINGS FIRST", "STEPHEN COVEY"],
  ["ATTENTION IS THE RAREST FORM OF GENEROSITY", "SIMONE WEIL"],
];

export function quoteForHour(date = new Date()) {
  const idx = (date.getHours() * 7 + date.getDate()) % QUOTES.length;
  return QUOTES[idx];
}
